services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'True'
    ports:
      - '${PGADMIN_PORT}:80'
    volumes:
      # delete the pgadmin Docker volume if changes are needed
      - pgadmin_data:/var/lib/pgadmin
      - ./database/pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  tracker-api:
    build:
      context: ./services/tracker-api
      dockerfile: Dockerfile.dev
      args:
        USER_UID: 1000
        USER_GID: 1000
    container_name: dotnet-api
    working_dir: /workspace/services/tracker-api
    ports:
      - '${DOTNET_PORT}:${DOTNET_PORT}'
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: 'http://0.0.0.0:${DOTNET_PORT}'
      DOTNET_USE_POLLING_FILE_WATCHER: 'true'
      ConnectionStrings__DefaultConnection: >
        Host=postgres;
        Port=${POSTGRES_PORT};
        Database=${POSTGRES_DB};
        Username=${POSTGRES_USER};
        Password=${POSTGRES_PASSWORD};
        SSL Mode=${POSTGRES_SSL_MODE};
        Trust Server Certificate=true
    volumes:
      - .:/workspace
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy
    user: '1000:1000'
    command: dotnet watch run --hot-reload --urls http://0.0.0.0:${DOTNET_PORT}

  tracker-ui:
    build:
      context: .
      dockerfile: ui/tracker-ui/Dockerfile.dev
      args:
        USER_UID: 1000
        USER_GID: 1000
    container_name: tracker-ui
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: ${NODE_ENV}
      NEXT_PUBLIC_API_URL: 'http://tracker-api:${DOTNET_PORT}'
      WATCHPACK_POLLING: 'true'
    volumes:
      - .:/workspace
    networks:
      - app-network
    depends_on:
      - tracker-api
    working_dir: /workspace/ui/tracker-ui
    user: '1000:1000'
    command: npx nx dev tracker-ui -- --hostname 0.0.0.0

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
  pgadmin_data:
