services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    env_file: .env

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - ./database/volumes/postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  tracker-api:
    build:
      context: ./services/tracker-api
      dockerfile: Dockerfile.dev
    container_name: tracker-api
    ports:
      - '${DOTNET_PORT}:${DOTNET_PORT}'
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: 'http://0.0.0.0:${DOTNET_PORT}'
      ConnectionStrings__DefaultConnection: 'Host=postgres;Port=${POSTGRES_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}'
      DOTNET_USE_POLLING_FILE_WATCHER: 'true'
    volumes:
      - .:/workspace # Mount entire monorepo
      - /workspace/services/tracker-api/bin # Exclude bin
      - /workspace/services/tracker-api/obj # Exclude obj
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy
    command: sleep infinity

  tracker-ui:
    build:
      context: .
      dockerfile: ui/tracker-ui/Dockerfile.dev
    container_name: tracker-ui
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: ${NODE_ENV}
      NEXT_PUBLIC_API_URL: 'http://tracker-api:${DOTNET_PORT}'
      WATCHPACK_POLLING: 'true' # Enable polling for WSL file watching
    volumes:
      - .:/workspace # Mount entire monorepo
      - /workspace/node_modules
      - /workspace/ui/tracker-ui/.next
      - /workspace/ui/tracker-ui/node_modules
    networks:
      - app-network
    depends_on:
      - tracker-api
    command: sleep infinity

networks:
  app-network:
    driver: bridge
