services:
  postgres:
    build:
      context: ./database/postgres
    container_name: postgres_db
    env_file: .env

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - ./database/volumes/postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  tracker-api:
    build:
      context: ./services/tracker-api
      dockerfile: Dockerfile.dev
    container_name: tracker-api
    ports:
      - '${DOTNET_PORT}:${DOTNET_PORT}'
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: ${ASPNETCORE_URLS}
      ConnectionStrings__DefaultConnection: 'Host=postgres;Port=${POSTGRES_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}'
      DOTNET_USE_POLLING_FILE_WATCHER: 'true'
    volumes:
      - ./services/tracker-api:/app
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy
    command: sleep infinity

networks:
  app-network:
    driver: bridge
